/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const panel: string;
declare const sourceLens: string;
declare const locationString: string;
declare const sourceCode: string;
declare const sourceLensOverlay: string;
declare const panelTitle: string;
declare const panelAction: string;
declare const active: string;
declare const panelGroup: string;

export {
	panel,
	sourceLens,
	locationString,
	sourceCode,
	sourceLensOverlay,
	panelTitle,
	panelAction,
	active,
	panelGroup
};

declare const __default_export__: {
	panel: typeof panel;
	sourceLens: typeof sourceLens;
	locationString: typeof locationString;
	sourceCode: typeof sourceCode;
	sourceLensOverlay: typeof sourceLensOverlay;
	panelTitle: typeof panelTitle;
	panelAction: typeof panelAction;
	active: typeof active;
	panelGroup: typeof panelGroup;
};
export default __default_export__;
