/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const sourceLens: string;
declare const sourceLensOverlay: string;

export {
	sourceLens,
	sourceLensOverlay
};

declare const __default_export__: {
	sourceLens: typeof sourceLens;
	sourceLensOverlay: typeof sourceLensOverlay;
};
export default __default_export__;
